[package]
name = "sailfish"
version = "0.1.0"
edition = "2018"
authors = ["J. Zrake <jzrake@clemson.edu>", "A. MacFadyen <macfadyen@nyu.edu>"]
description = "fast code to simulate binary accretion"

[dependencies]
kepler-two-body = { git = "https://github.com/clemson-cal/kepler-two-body" }
kind-config = "0.2"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "0.15"

[build-dependencies]
cc = "1.0"

[features]
default = ["omp"]
omp = []
cuda = []
