[package]
name = "gpu_core"
version = "0.1.0"
authors = ["Jonathan Zrake <jonathan.zrake@gmail.com>"]
edition = "2018"

[dependencies]
once_cell = "1.8.0"

[build-dependencies]
cc = "1.0"
sf_build = { path = "../sf_build" }
