[package]
name = "gpu_mem"
version = "0.1.0"
authors = ["Jonathan Zrake <jonathan.zrake@gmail.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
cc = "1.0"
sf_build = { path = "../sf_build" }
